.PHONY: clean All

All:
	@echo "----------Building project:[ HowFunctionCallWorks - Debug ]----------"
	@cd "HowFunctionCallWorks" && "$(MAKE)" -f  "HowFunctionCallWorks.mk"
clean:
	@echo "----------Cleaning project:[ HowFunctionCallWorks - Debug ]----------"
	@cd "HowFunctionCallWorks" && "$(MAKE)" -f  "HowFunctionCallWorks.mk" clean
