.PHONY: clean All

All:
	@echo "----------Building project:[ ScopeExamples - Debug ]----------"
	@cd "ScopeExamples" && "$(MAKE)" -f  "ScopeExamples.mk"
clean:
	@echo "----------Cleaning project:[ ScopeExamples - Debug ]----------"
	@cd "ScopeExamples" && "$(MAKE)" -f  "ScopeExamples.mk" clean
