.PHONY: clean All

All:
	@echo "----------Building project:[ CompilerWarnnings - Debug ]----------"
	@cd "CompilerWarnnings" && "$(MAKE)" -f  "CompilerWarnnings.mk"
clean:
	@echo "----------Cleaning project:[ CompilerWarnnings - Debug ]----------"
	@cd "CompilerWarnnings" && "$(MAKE)" -f  "CompilerWarnnings.mk" clean
