.PHONY: clean All

All:
	@echo "----------Building project:[ RangeBaseForLoop - Debug ]----------"
	@cd "RangeBaseForLoop" && "$(MAKE)" -f  "RangeBaseForLoop.mk"
clean:
	@echo "----------Cleaning project:[ RangeBaseForLoop - Debug ]----------"
	@cd "RangeBaseForLoop" && "$(MAKE)" -f  "RangeBaseForLoop.mk" clean
