.PHONY: clean All

All:
	@echo "----------Building project:[ BoxShape - Debug ]----------"
	@cd "BoxShape" && "$(MAKE)" -f  "BoxShape.mk"
clean:
	@echo "----------Cleaning project:[ BoxShape - Debug ]----------"
	@cd "BoxShape" && "$(MAKE)" -f  "BoxShape.mk" clean
