.PHONY: clean All

All:
	@echo "----------Building project:[ InitilizingVariables - Debug ]----------"
	@cd "InitilizingProjects" && "$(MAKE)" -f  "InitilizingVariables.mk"
clean:
	@echo "----------Cleaning project:[ InitilizingVariables - Debug ]----------"
	@cd "InitilizingProjects" && "$(MAKE)" -f  "InitilizingVariables.mk" clean
