.PHONY: clean All

All:
	@echo "----------Building project:[ ConstructorsInitilizationLists - Debug ]----------"
	@cd "ConstructorsInitilizationLists" && "$(MAKE)" -f  "ConstructorsInitilizationLists.mk"
clean:
	@echo "----------Cleaning project:[ ConstructorsInitilizationLists - Debug ]----------"
	@cd "ConstructorsInitilizationLists" && "$(MAKE)" -f  "ConstructorsInitilizationLists.mk" clean
