.PHONY: clean All

All:
	@echo "----------Building project:[ ImplementingThroughHeaderSeparateFiles - Debug ]----------"
	@cd "ImplementingThroughHeaderSeparateFiles" && "$(MAKE)" -f  "ImplementingThroughHeaderSeparateFiles.mk"
clean:
	@echo "----------Cleaning project:[ ImplementingThroughHeaderSeparateFiles - Debug ]----------"
	@cd "ImplementingThroughHeaderSeparateFiles" && "$(MAKE)" -f  "ImplementingThroughHeaderSeparateFiles.mk" clean
