.PHONY: clean All

All:
	@echo "----------Building project:[ ReturnPointers - Debug ]----------"
	@cd "ReturnPointers" && "$(MAKE)" -f  "ReturnPointers.mk"
clean:
	@echo "----------Cleaning project:[ ReturnPointers - Debug ]----------"
	@cd "ReturnPointers" && "$(MAKE)" -f  "ReturnPointers.mk" clean
