.PHONY: clean All

All:
	@echo "----------Building project:[ ArrayVsPointersRelationship - Debug ]----------"
	@cd "ArrayVsPointersRelationship" && "$(MAKE)" -f  "ArrayVsPointersRelationship.mk"
clean:
	@echo "----------Cleaning project:[ ArrayVsPointersRelationship - Debug ]----------"
	@cd "ArrayVsPointersRelationship" && "$(MAKE)" -f  "ArrayVsPointersRelationship.mk" clean
