.PHONY: clean All

All:
	@echo "----------Building project:[ ArrVsPointersStackOverflowExample - Debug ]----------"
	@cd "ArrayVsPointersRelationship" && "$(MAKE)" -f  "ArrVsPointersStackOverflowExample.mk"
clean:
	@echo "----------Cleaning project:[ ArrVsPointersStackOverflowExample - Debug ]----------"
	@cd "ArrayVsPointersRelationship" && "$(MAKE)" -f  "ArrVsPointersStackOverflowExample.mk" clean
