.PHONY: clean All

All:
	@echo "----------Building project:[ MyString-start - Debug ]----------"
	@cd "MyString-start" && "$(MAKE)" -f  "MyString-start.mk"
clean:
	@echo "----------Cleaning project:[ MyString-start - Debug ]----------"
	@cd "MyString-start" && "$(MAKE)" -f  "MyString-start.mk" clean
